variables:
  TAG: $CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA
  AWS_REGISTRY: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  AWS_REGISTRY_IMAGE: $AWS_REGISTRY/globaleaks
  GITLAB_REGISTRY_IMAGE: $CI_REGISTRY_IMAGE

default:
  image: bentolor/docker-dind-awscli
  services:
    - docker:dind
  before_script:
    - printf "%s" "${CI_REGISTRY_PASSWORD}" | docker login --username ${CI_REGISTRY_USER} --password-stdin $CI_REGISTRY
    - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_REGISTRY

stages:
  - build

build-main:
  stage: build
  only:
    - main
  services:
    - docker:dind
  script:
    - docker build -t $GITLAB_REGISTRY_IMAGE:$TAG -t $GITLAB_REGISTRY_IMAGE:latest -t $AWS_REGISTRY_IMAGE:$TAG -t $AWS_REGISTRY_IMAGE:latest . -f docker/Dockerfile.deploy
    - docker push $GITLAB_REGISTRY_IMAGE:$TAG
    - docker push $GITLAB_REGISTRY_IMAGE:latest
    - docker push $AWS_REGISTRY_IMAGE:$TAG
    - docker push $AWS_REGISTRY_IMAGE:latest

build-develop:
  stage: build
  only:
    - develop
  services:
    - docker:dind
  script:
    - docker build -t $GITLAB_REGISTRY_IMAGE:$TAG -t $GITLAB_REGISTRY_IMAGE:latest . -f docker/Dockerfile.deploy
    - docker push $GITLAB_REGISTRY_IMAGE:$TAG
    - docker push $GITLAB_REGISTRY_IMAGE:latest
