variables:
  AWS_REGISTRY: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  AWS_REGISTRY_IMAGE: $AWS_REGISTRY/globaleaks
  AWS_REGISTRY_IMAGE_TAG: $AWS_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA
  GITLAB_REGISTRY_IMAGE: $CI_REGISTRY_IMAGE
  GITLAB_REGISTRY_IMAGE_TAG: $GITLAB_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA

default:
  image: bentolor/docker-dind-awscli
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_REGISTRY

stages:
  - build
  - push

build:
  stage: build
  services:
    - docker:dind
  script:
    - docker build -t $GITLAB_REGISTRY_IMAGE_TAG -t $GITLAB_REGISTRY_IMAGE:latest -t $AWS_REGISTRY_IMAGE_TAG -t $AWS_REGISTRY_IMAGE:latest . -f docker/Dockerfile.deploy

push-dev:
  stage: push
  only: 
    - develop
  script:
    - docker push $GITLAB_REGISTRY_IAMGE_TAG
    - docker push $GITLAB_REGISTRY_IMAGE:latest
    
push-main:
  stage: push
  only:
    - main
  script:
    - docker push $GITLAB_REGISTRY_IMAGE_TAG
    - docker push $GITLAB_REGISTRY_IMAGE:latest
    - docker push $AWS_REGISTRY_IMAGE_TAG
    - docker push $AWS_REGISTRY_IMAGE:latest
