variables:
  AWS_REGISTRY: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  AWS_REGISTRY_IMAGE: $AWS_REGISTRY/globaleaks
  GITLAB_REGISTRY_IMAGE: $CI_REGISTRY_IMAGE

default:
  image: bentolor/docker-dind-awscli
  services:
    - docker:dind
  before_script:
    - printf "%s" "${CI_REGISTRY_PASSWORD}" | docker login --username ${CI_REGISTRY_USER} --password-stdin $CI_REGISTRY
    - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_REGISTRY

stages:
  - prebuild
  - build
  - prepare
  - release

prebuild:
  stage: prebuild
  rules:
    - if: $CI_COMMIT_TAG != null
      when: always
    - if: $CI_COMMIT_TAG == null
      when: never
  script:
    - |
      if [ -z "$CI_COMMIT_TAG" ]; then echo "❌ ERROR: CI_COMMIT_TAG is not set!"; exit 1; fi
      TAG=$(echo "$CI_COMMIT_TAG" | sed 's/-luna$//')
      VERSION="${TAG#v}"
    - echo "TAG=${TAG}" >> variables.env
    - echo "VERSION=${VERSION}" >> variables.env
  artifacts:
    reports:
      dotenv: variables.env

build-develop:
  variables:
    TAG: $CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA
  stage: build
  only:
    - develop
  script:
    - |
      if [ -z "$TAG" ]; then echo "❌ ERROR: TAG is not set!"; exit 1; fi
      docker build -t $GITLAB_REGISTRY_IMAGE:$TAG -t $GITLAB_REGISTRY_IMAGE:latest . -f docker/Dockerfile.deploy
      docker push $GITLAB_REGISTRY_IMAGE:$TAG
      docker push $GITLAB_REGISTRY_IMAGE:latest

build-main:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG != null
      when: always
    - if: $CI_COMMIT_TAG == null
      when: never
  script:
    - |
      docker build \
      -t $GITLAB_REGISTRY_IMAGE:$VERSION \
      -t $GITLAB_REGISTRY_IMAGE:latest \
      -t $AWS_REGISTRY_IMAGE:$VERSION \
      -t $AWS_REGISTRY_IMAGE:latest \
      . -f docker/Dockerfile.deploy
      docker push $GITLAB_REGISTRY_IMAGE:$VERSION
      docker push $GITLAB_REGISTRY_IMAGE:latest
      docker push $AWS_REGISTRY_IMAGE:$VERSION
      docker push $AWS_REGISTRY_IMAGE:latest
    - echo "TAG=${TAG}" >> variables.env
    - echo "VERSION=${VERSION}" >> variables.env
  artifacts:
    reports:
      dotenv: variables.env

prepare:
  stage: prepare
  needs:
    - build-main
  rules:
    - if: $CI_COMMIT_TAG != null
      when: always
    - if: $CI_COMMIT_TAG == null
      when: never
  before_script: []
  script:
    - |
      echo "Preparing GitLab Release for tag: $TAG"
      awk -v version="Changes in version $VERSION" '
          $0 ~ version {flag=1; print; next}
          flag && /^[[:space:]]*$/ {exit}
          flag {print}
      ' CHANGELOG > RELEASE_DESCRIPTION.txt
      echo "" >> RELEASE_DESCRIPTION.txt
      echo "" >> RELEASE_DESCRIPTION.txt
      echo "Docker Image AWS" >> RELEASE_DESCRIPTION.txt
      echo "  Registry: $AWS_REGISTRY_IMAGE:$VERSION" >> RELEASE_DESCRIPTION.txt
      echo "  Pull Command: docker pull $AWS_REGISTRY_IMAGE:$VERSION" >> RELEASE_DESCRIPTION.txt
      echo "" >> RELEASE_DESCRIPTION.txt
      echo "Docker Image GitLab" >> RELEASE_DESCRIPTION.txt
      echo "  Registry: $GITLAB_REGISTRY_IMAGE:$VERSION" >> RELEASE_DESCRIPTION.txt
      echo "  Pull Command: docker pull $GITLAB_REGISTRY_IMAGE:$VERSION" >> RELEASE_DESCRIPTION.txt
    - echo "TAG=${TAG}" >> variables.env
    - echo "VERSION=${VERSION}" >> variables.env
  artifacts:
    paths:
      - RELEASE_DESCRIPTION.txt
    reports:
      dotenv: variables.env

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  services: []
  before_script:
    - RELEASE_DESCRIPTION="$(cat RELEASE_DESCRIPTION.txt)"
  rules:
    - if: $CI_COMMIT_TAG != null
      when: always
    - if: $CI_COMMIT_TAG == null
      when: never
  needs:
    - job: prepare
      artifacts: true
  script:
    - echo "Running release-job for $TAG"
  release:
    name: 'Release ${TAG}'
    description: '${RELEASE_DESCRIPTION}'
    ref: '${CI_COMMIT_TAG}'
